#!/bin/zsh

# XDG basedir defaults:
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

# Export ZDOTDIR if it exists:
[ -d "$HOME/.config/zsh" ] && export ZDOTDIR="$HOME/.config/zsh"
